### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by flbyrne** [asappresearch/webagents-step#1]
I would like to try the evaluations, but it would be nice to have a requirements.txt file to make it easier to use. Thanks in advance!

**Comment by psodhi** [comment]
Thanks for pointing this out! I have added a `requirements.txt `.

**Comment by psodhi** [comment]
Thanks so much for pointing this out! I have added a `requirements.txt`

**Comment by psodhi-asapp** [comment]
Thanks for pointing this out! I have added a `requirements.txt`
